{"name": "Возврат ошибки при неправильном значение поля", "status": "passed", "description": "Проверка, что при неправильном значение поля, возвращается кода 404 и текст ошибки в теле ответа", "steps": [{"name": "Отправка POST-запроса для авторизации курьера", "status": "passed", "start": 1739104077684, "stop": 1739104077802}, {"name": "Проверка, что код ответа на создание заказа 404", "status": "passed", "start": 1739104077802, "stop": 1739104077802}, {"name": "Проверка, что в теле ответа содержится сообщение об ошибки", "status": "passed", "start": 1739104077802, "stop": 1739104077802}], "parameters": [{"name": "incorrect_field", "value": "'login'"}], "start": 1739104077684, "stop": 1739104077803, "uuid": "d0d52971-89b1-490d-8fc7-22f425971bfe", "historyId": "a85fa411bbe7d7019aeaa77e04a31c2c", "testCaseId": "51569ab39f17883721bc826a2a78674c", "fullName": "tests.test_auth_courier.TestAuthCourier#test_courier_login_incorrect_field_returns_error", "labels": [{"name": "story", "value": "Логин курьера в системе"}, {"name": "feature", "value": "Работа с курьером"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_courier"}, {"name": "subSuite", "value": "TestAuthCourier"}, {"name": "host", "value": "bnovo-nb-0056"}, {"name": "thread", "value": "25888-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_courier"}]}